name: CI/CD Pipeline

on:
  push:
    branches:
      - staging    # Trigger on pushes to the staging branch
      - production  # Trigger on pushes to the production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Specify your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the application
      - name: Build the application
        run: npm run build

      # Step 5: Deploy to server
      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}        # Your server IP or domain
          username: ${{ secrets.USERNAME }}  # SSH username
          key: ${{ secrets.KEY }}            # SSH private key
          source: "."
          # Use conditionals to set the target based on the branch
          target: ${{ github.ref == 'refs/heads/staging' && '/home/vpn-user/Projects/staging' || '/home/vpn-user/Projects/production' }}

      # Step 6: Start/Restart the application with PM2
      - name: Start/Restart application
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
          if [ '${{ github.ref }}' = 'refs/heads/staging' ]; then
              pm2 start app.js --name smile-app-staging  || pm2 restart smile-app-staging ;
          else
              pm2 start app.js --name smile-app-production   || pm2 restart smile-app-production  ;
          fi"

