name: CI/CD

on:
  push:
    branches:
      - staging  # Trigger on pushes to staging
      - main      # Trigger on pushes to production (main)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            cd ~/Projects/staging  # Path for staging
          else
            cd ~/Projects/production  # Path for production
          fi
          npm install
          npm run build
          npm run start
