// countyCodes.js

const countyCodes = {
    "Aberconwy and Colwyn": "I0",
    "Aberdeen City": "I1",
    "Aberdeenshire": "I2",
    "Anglesey": "I3",
    "Angus": "I4",
    "Antrim": "I5",
    "Argyll and Bute": "I6",
    "Armagh": "I7",
    "Avon": "I8",
    "Ayrshire": "I9",
    "Bath and NE Somerset": "IB",
    "Bedfordshire": "IC",
    "Belfast": "IE",
    "Berkshire": "IF",
    "Berwickshire": "IG",
    "BFPO": "IH",
    "Blaenau Gwent": "II",
    "Buckinghamshire": "IJ",
    "Caernarfonshire": "IK",
    "Caerphilly": "IM",
    "Caithness": "IO",
    "Cambridgeshire": "IP",
    "Cardiff": "IQ",
    "Cardiganshire": "IR",
    "Carmarthenshire": "IS",
    "Ceredigion": "IT",
    "Channel Islands": "IU",
    "Cheshire": "IV",
    "City of Bristol": "IW",
    "Clackmannanshire": "IX",
    "Clwyd": "IY",
    "Conwy": "IZ",
    "Cornwall/Scilly": "J0",
    "Cumbria": "J1",
    "Denbighshire": "J2",
    "Derbyshire": "J3",
    "Derry/Londonderry": "J4",
    "Devon": "J5",
    "Dorset": "J6",
    "Down": "J7",
    "Dumfries and Galloway": "J8",
    "Dunbartonshire": "J9",
    "Dundee": "JA",
    "Durham": "JB",
    "Dyfed": "JC",
    "East Ayrshire": "JD",
    "East Dunbartonshire": "JE",
    "East Lothian": "JF",
    "East Renfrewshire": "JG",
    "East Riding Yorkshire": "JH",
    "East Sussex": "JI",
    "Edinburgh": "JJ",
    "England": "JK",
    "Essex": "JL",
    "Falkirk": "JM",
    "Fermanagh": "JN",
    "Fife": "JO",
    "Flintshire": "JP",
    "Glasgow": "JQ",
    "Gloucestershire": "JR",
    "Greater London": "JS",
    "Greater Manchester": "JT",
    "Gwent": "JU",
    "Gwynedd": "JV",
    "Hampshire": "JW",
    "Hartlepool": "JX",
    "Hereford and Worcester": "HAW",
    "Hertfordshire": "JY",
    "Highlands": "JZ",
    "Inverclyde": "K0",
    "Inverness-Shire": "K1",
    "Isle of Man": "K2",
    "Isle of Wight": "K3",
    "Kent": "K4",
    "Kincardinshire": "K5",
    "Kingston Upon Hull": "K6",
    "Kinross-Shire": "K7",
    "Kirklees": "K8",
    "Lanarkshire": "K9",
    "Lancashire": "KA",
    "Leicestershire": "KB",
    "Lincolnshire": "KC",
    "Londonderry": "KD",
    "Merseyside": "KE",
    "Merthyr Tydfil": "KF",
    "Mid Glamorgan": "KG",
    "Mid Lothian": "KI",
    "Middlesex": "KH",
    "Monmouthshire": "KJ",
    "Moray": "KK",
    "Neath & Port Talbot": "KL",
    "Newport": "KM",
    "Norfolk": "KN",
    "North Ayrshire": "KP",
    "North East Lincolnshire": "KQ",
    "North Lanarkshire": "KR",
    "North Lincolnshire": "KT",
    "North Somerset": "KU",
    "North Yorkshire": "KV",
    "Northamptonshire": "KO",
    "Northern Ireland": "KW",
    "Northumberland": "KX",
    "Nottinghamshire": "KZ",
    "Orkney and Shetland Isles": "L0",
    "Oxfordshire": "L1",
    "Pembrokeshire": "L2",
    "Perth and Kinross": "L3",
    "Powys": "L4",
    "Redcar and Cleveland": "L5",
    "Renfrewshire": "L6",
    "Rhonda Cynon Taff": "L7",
    "Rutland": "L8",
    "Scottish Borders": "L9",
    "Shetland": "LB",
    "Shropshire": "LC",
    "Somerset": "LD",
    "South Ayrshire": "LE",
    "South Glamorgan": "LF",
    "South Gloucestershire": "LG",
    "South Lanarkshire": "LH",
    "South Yorkshire": "LI",
    "Staffordshire": "LJ",
    "Stirling": "LK",
    "Stockton On Tees": "LL",
    "Suffolk": "LM",
    "Surrey": "LN",
    "Swansea": "LO",
    "Torfaen": "LP",
    "Tyne and Wear": "LQ",
    "Tyrone": "LR",
    "Vale Of Glamorgan": "LS",
    "Wales": "LT",
    "Warwickshire": "LU",
    "West Berkshire": "LV",
    "West Dunbartonshire": "LW",
    "West Glamorgan": "LX",
    "West Lothian": "LY",
    "West Midlands": "LZ",
    "West Sussex": "M0",
    "West Yorkshire": "M1",
    "Western Isles": "M2",
    "Wiltshire": "M3",
    "Wirral": "M4",
    "Worcestershire": "M5",
    "Wrexham": "M6",
    "York": "M7"
};

export const getCountyCode = (countyName) => {
    return countyCodes[countyName] || null;
};
